apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: opa
build:
  artifacts:
    - image: warpcomdev/kube-mgmt
      context: .
      docker:
        buildArgs:
          VERSION: "{{.VERSION}}"
          COMMIT: "{{.COMMIT}}"
  local:
    push: true
    useBuildkit: true
profiles:
  - name: local
    activation:
      - kubeContext: k3d-kube-mgmt
    deploy:
      helm:
        releases:
          - name: opa
            chartPath: charts/opa
            wait: true
            upgradeOnChange: false
            skipBuildDependencies: true
            artifactOverrides:
              mgmt.image: warpcomdev/kube-mgmt
            imageStrategy:
              helm: {}
  - name: e2e
    deploy:
      helm:
        releases:
          - name: opa
            chartPath: charts/opa
            wait: true
            upgradeOnChange: false
            skipBuildDependencies: true
            valuesFiles:
              - test/e2e/values-e2e.yaml
            artifactOverrides:
              mgmt.image: warpcomdev/kube-mgmt
            imageStrategy:
              helm: {}
